name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Add a step to list the contents of the source directory before rsync
      - name: List Source Directory Contents
        run: ls -al

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          
          # Use rsync to copy files to the remote server
          # Use double quotes for better readability
          rsync -e "ssh -o StrictHostKeyChecking=no -i $(pwd)/deploy_key" -r --delete-after ./ ubuntu@ec2-54-163-35-94.compute-1.amazonaws.com:~/github-actions-demo
          
          # SSH into the remote server and execute deployment commands
          ssh -o StrictHostKeyChecking=no -i $(pwd)/deploy_key ubuntu@ec2-54-163-35-94.compute-1.amazonaws.com '
            cd ~/github-actions-demo &&         # Navigate to the project directory
            git pull &&                        # Pull the latest changes from the repository
            npm install &&                     # Install npm dependencies
            npm run build &&                   # Build the NestJS application
            pm2 restart all                    # Restart the application with PM2
          ' > deploy_log.txt 2>&1

      - name: Upload Deploy Logs
        uses: actions/upload-artifact@v2
        with:
          name: deploy-logs
          path: deploy_log.txt
