name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          rsync -e "ssh -o StrictHostKeyChecking=no -i $(pwd)/deploy_key" -r --delete-after ./ ubuntu@ec2-54-163-35-94.compute-1.amazonaws.com:~/github-actions-demo
          ssh -o StrictHostKeyChecking=no -i $(pwd)/deploy_key ubuntu@ec2-54-163-35-94.compute-1.amazonaws.com 'cd ~/github-actions-demo && git pull && npm install && pm2 restart all' > deploy_log.txt 2>&1

      - name: Upload Deploy Logs
        uses: actions/upload-artifact@v2
        with:
          name: deploy-logs
          path: deploy_log.txt
