name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          ssh ubuntu@ec2-3-88-45-113.compute-1.amazonaws.com 'cd github-actions-demo && git pull && npm install && pm2 restart all'
